# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    
    - name: Install dependencies
      run: dotnet restore
    
    - name: Build
      id: dotnet-build
      run: dotnet build --no-restore

    - name: Test
      id: dotnet-test
      if: always() && steps.dotnet-build.outcome == 'success'
      run: dotnet test --no-restore --verbosity normal

    - name: Create package
      id: dotnet-create-package
      if: always() && steps.dotnet-test.outcome == 'success'
      run: dotnet publish -c Release -p DevopsWebApp --property:PublishDir='${{ github.workspace }}/DevopsTakeHomePackage'
      working-directory: ${{ github.workspace}}/DevopsWebApp
        
    - name: Zip package
      id: zip-package
      if: always() && steps.dotnet-create-package.outcome == 'success'
      run: zip -r ${{ github.workspace}}/DevopsWebApp.zip ${{ github.workspace }}/DevopsTakeHomePackage

    - name: Configure AWS Credentials
      id: configure-aws
      uses: aws-actions/configure-aws-credentials@v3
      if: always() && steps.zip-package.outcome == 'success'
      with:
        aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Copy package to S3
      if: always() && steps.configure-aws.outcome == 'success'
      run: aws s3 cp ${{ github.workspace}}/DevopsWebApp.zip s3://${{ vars.AWS_BUCKET }}/